/**
 * Single home for RU user-facing strings (ROADMAP §3). Vocabulary must match
 * CONTEXT.md; body text stays ≥16 sp per the UX constraints.
 */
const SPECIES_NAMES: Record<string, string> = {
  sp1: "Вид 1",
  sp2: "Вид 2",
  sp3: "Вид 3",
};

const COLOR_NAMES: Record<string, string> = {
  c1: "Окрас 1",
  c2: "Окрас 2",
  c3: "Окрас 3",
};

const ACCESSORY_NAMES: Record<string, string> = {
  a1: "Аксессуар 1",
  a2: "Аксессуар 2",
  a3: "Аксессуар 3",
};

const POSE_NAMES = {
  idle: "спокойный",
  happy: "весёлый",
  sad: "грустный",
} as const;

export const strings = {
  appName: "ФинПет",
  versionLine: (version: string, build: number) => `версия ${version} (${build})`,

  skip: "Пропустить",
  next: "Дальше",
  play: "Играть!",
  playTask: "Играть",
  gotIt: "Понятно",
  done: "Готово",
  close: "Закрыть",
  back: "Назад",
  howToPlay: "Как играть",
  settings: "Настройки",
  deleteProfile: "Удалить профиль",
  devSection: "Dev",
  finishDay: "Закончить день",
  composePlanHint: "Составь план дня",
  planReady: "План готов",
  finishDayNeedPlan: "Сначала составь план дня",
  daySummaryTitle: "Итоги дня",
  waitTomorrow: "Ждём завтра!",
  nextDay: "Следующий день",
  waitingBanner: "Новый день откроется завтра",
  waitingEconomyHint: "Откроется завтра",
  waitingLockIcon: "⏳",
  scoreMandatory: "Обязательные",
  scoreWithinPlan: "По плану",
  scoreDeposit: "Копилка",
  scoreYesIcon: "✅",
  scoreNoIcon: "⚠️",
  scoreFact: (word: string, points: number) => `${word} ${points > 0 ? `+${points}` : "+0"}`,
  meterReasonCareSkip: "Забота -15: обязательное не купили.",
  meterReasonMoodOverspend: "Настроение -5: желаемое сверх плана.",
  meterReasonUnchanged: (label: string) => `${label} без изменений`,
  nextDayPlanNeeds: "Завтра сначала запланируй обязательное.",
  allowanceRibbon: "Пособие +10 монет",

  feedbackBalance: (n: number) => `Баланс ${n > 0 ? "+" : ""}${n}`,
  feedbackSavings: (n: number) => `Копилка ${n > 0 ? "+" : ""}${n}`,
  feedbackCare: (n: number) => `Забота ${n > 0 ? "+" : ""}${n}`,
  feedbackMood: (n: number) => `Настроение ${n > 0 ? "+" : ""}${n}`,
  feedbackCauseAllowance: "Потому что начался новый игровой день.",
  feedbackNextAllowance: "Что дальше: составь план дня.",
  feedbackCausePurchase: "Потому что ты купил вещь для питомца.",
  feedbackNextPurchase: "Что дальше: сверься с планом или отложи в копилку.",
  feedbackCauseSavingsIn: "Потому что ты положил монеты в копилку.",
  feedbackNextSavingsIn: "Что дальше: копи дальше или вернись к плану дня.",
  feedbackCauseSavingsOut: "Потому что ты забрал монеты из копилки.",
  feedbackNextSavingsOut: "Что дальше: подумай, нужна ли трата сегодня.",
  feedbackCauseGoal: "Потому что копилка дошла до цели.",
  feedbackNextGoal: "Что дальше: выбери новую цель, если хочешь копить снова.",

  shopMandatoryTab: "Обязательное",
  shopOptionalTab: "Желаемое",
  shopPrice: (n: number) => `${n} монет`,
  shopCategory: (kind: "mandatory" | "optional") =>
    kind === "mandatory" ? "Обязательные" : "Желаемые",
  shopAfterBuy: (n: number) => `после покупки: ${n} монет`,
  shopImpact: (meter: string, delta: number) => `эффект: ${meter} +${delta}`,
  shopBought: "Куплено",
  shopBuy: "Купить",
  shopPostpone: "Отложить",
  shopConfirmBuy: (name: string, price: number) => `Купить ${name} за ${price}?`,
  shopBlocked: (n: number) => `Не хватает ${n} монет`,
  shopWaitAllowance: "Дождаться пособия",
  shopDoTask: "Выполнить задание",
  shopWaitExplain: "Пособие придёт в следующий игровой день. Можно сделать задание или отложить покупку.",

  savingsPot: (n: number) => `В копилке ${n}`,
  savingsEstimateNone: "—",
  savingsEstimate: (n: number) => `примерно ${n} дн.`,
  savingsDeposit: "Положить",
  savingsWithdraw: "Забрать",
  savingsDepositAmount: "Сумма",
  savingsConfirmDeposit: (n: number) => `Положить ${n}?`,
  savingsConfirmWithdraw: (n: number) => `Забрать ${n}?`,
  savingsWithdrawPreview: (potAfter: number, days: number) =>
    `В копилке станет ${potAfter}. Мечта отодвинется на ${days} дн.`,
  savingsWithdrawPreviewNone: (potAfter: number) => `В копилке станет ${potAfter}.`,
  savingsAchieved: "Мечта сбылась!",
  savingsConfetti: "🎉",
  savingsPickGoal: "Выбери новую цель",
  savingsAchievedBadge: "сбылась",
  savingsRemaining: (n: number) => `осталось ${n}`,

  tabResults: "Итоги",
  tabJournal: "Журнал",
  tabGlossary: "Словарик",
  resultsEmpty: "Итоги появятся после первого закрытого игрового дня.",
  resultsLastDay: (n: number) => `Игровой день ${n}`,
  resultsScore: (n: number) => `Итог ${n}`,
  resultsOverall: "Всего",
  resultsDaysPlayed: (n: number) => `Игровых дней: ${n}`,
  resultsTasksDone: (done: number, total: number) => `Задания ${done}/${total}`,
  resultsGoalsAchieved: (n: number) => `Целей: ${n}`,
  scoreMandatory: (earned: boolean) => (earned ? "Обязательные +2" : "Обязательные 0"),
  scoreWithinPlan: (earned: boolean) => (earned ? "По плану +1" : "По плану 0"),
  scoreDeposited: (earned: boolean) => (earned ? "Копилка +1" : "Копилка 0"),
  meterReasonSkippedMandatory: (n: number) => `Забота ${n}: пропущены обязательные расходы`,
  meterReasonOptionalOverspend: (n: number) => `Настроение ${n}: желаемое больше плана`,
  meterReasonNoChange: "Забота и настроение без изменений",
  journalStart: "Старт",
  journalDay: (n: number) => `День ${n}`,
  journalStartingGrant: "Стартовый бюджет",
  journalAllowance: "Пособие",
  journalPurchase: (name: string) => `Покупка: ${name}`,
  journalSavingsIn: "Перевод в копилку",
  journalSavingsOut: "Из копилки",
  journalTaskReward: (title: string) => `Задание: ${title}`,
  journalTaskScene: "Задание",
  journalAmount: (n: number) => `${n > 0 ? "+" : ""}${n}`,

  planAvailable: (n: number) => `Можно распределить: ${n}`,
  planRemainder: (n: number) => `Останется свободных: ${n}`,
  planOverBudget: "В плане больше монет, чем есть. Убавь суммы.",
  confirmPlan: "Подтвердить план",
  confirmPlanTitle: "Подтвердить план дня?",
  confirmPlanBody:
    "Ты решил, сколько пойдёт на обязательное, желаемое и копилку. После этого план дня не меняется.",
  planColPlan: "план",
  planColActual: "потрачено",
  bucketMandatory: "Обязательные",
  bucketOptional: "Желаемые",
  bucketSavings: "Копилка",
  bucketMinus: (label: string) => `${label}, меньше`,
  bucketPlus: (label: string) => `${label}, больше`,
  bucketValue: (label: string, n: number) => `${label} ${n}`,
  planVsActual: (plan: number, actual: number) => `план ${plan} · потрачено ${actual}`,

  firstRunPet: "Питомец",
  firstRunNames: "Имена",
  howToPlayStep: (step: number, total: number) => `Шаг ${step} из ${total}`,
  petSays: (petName: string, message: string) => `Питомец ${petName} говорит: ${message}`,
  nameValidation: "Введи от 1 до 20 символов",
  firstRunSaveFailed: "Не получилось начать игру. Попробуй ещё раз.",
  playerNameLabel: "Как тебя зовут в игре?",
  petNameLabel: "Как зовут питомца?",
  speciesLegend: "Вид",
  colorLegend: "Окрас",
  accessoryLegend: "Аксессуар",
  speciesName: (key: string) => SPECIES_NAMES[key] ?? key,
  colorName: (key: string) => COLOR_NAMES[key] ?? key,
  accessoryName: (key: string) => ACCESSORY_NAMES[key] ?? key,

  startingBudgetTitle: "Тебе дали 100 монет на старт!",
  startingBudgetBody: "Это твой бюджет. Планируй, копи, заботься о питомце",

  care: "Забота",
  careIcon: "🐾",
  mood: "Настроение",
  moodIcon: "☀",
  meterLine: (label: string, value: number) => `${label} ${value}`,
  balanceWord: "Баланс",
  savingsWord: "Копилка",
  stageWord: "Этап",
  balanceBadge: (n: number) => `Баланс ${n}`,
  savingsBadge: (n: number) => `Копилка ${n}`,
  goalRatio: (have: number, cost: number) => `${have} / ${cost}`,
  goalRemaining: (n: number) => `осталось ${n}`,
  selectedCheck: "✓",
  stageIcon: "★",
  balanceIcon: "🪙",
  savingsIcon: "🐷",
  navPlanPictogram: "📋",
  navShopPictogram: "🛒",
  navSavingsPictogram: "🐷",
  navTasksPictogram: "🎯",
  navProgressPictogram: "📚",
  navAdultPictogram: "👤",
  poseIdle: POSE_NAMES.idle,
  poseHappy: POSE_NAMES.happy,
  poseSad: POSE_NAMES.sad,
  petA11y: (input: {
    petName?: string;
    species: string;
    color: string;
    accessory: string;
    pose: keyof typeof POSE_NAMES;
  }) => {
    const who = input.petName ? `Питомец ${input.petName}` : "Питомец";
    return `${who}, ${SPECIES_NAMES[input.species] ?? input.species}, ${COLOR_NAMES[input.color] ?? input.color}, ${ACCESSORY_NAMES[input.accessory] ?? input.accessory}, ${POSE_NAMES[input.pose]}`;
  },

  navPlan: "План",
  navShop: "Магазин",
  navSavings: "Копилка",
  navTasks: "Задания",
  navProgress: "Прогресс",
  navAdult: "Взрослый раздел",

  demoMode: "Демо-режим",
  demoName: "Демо",
  demoConfirmBody: "Демо создаёт отдельный тестовый профиль",
  demoBanner: "Демо: дни идут подряд",
  demoReset: "Сбросить демо",

  glossaryTitle: "Словарик",
  stubPlan: "Скоро: план дня. Пока вернись на главный экран.",
  stubShop: "Скоро: магазин. Пока вернись на главный экран.",
  stubSavings: "Скоро: копилка. Пока вернись на главный экран.",
  stubTasks: "Скоро: задания. Пока вернись на главный экран.",
} as const;
